package hu.ksh.idgs.worklist.service.impl;

public enum VisitStatusSendAcField implements VisitStatusSendField {

	SELF_LOADER("INTERNETEN_KITOLTOTT"), //

	ECONOMY_WITH_MODUL("GAZDASAGOK_MODULLAL"), //
	ECONOMY_WITHOUT_MODUL("GAZDASAGOK_MODUL_NELKUL"), //
	UNDER_LIMIT("KUSZOB_ALATT"), //
	NON_DATA_PROVIDER("NEM_ADATSZOLGALTATO"), //
	LOT("HAZTAJI_GAZDALKODAS"), //
	NEW_ECONOMY("UJ_GAZDASAG"), //
	STATUS_CATEGORY("STATUSZ_KATEGORIA"), //
	KSH_MAIL_FREQ("KSH_CIMEK_GYAKORISAGA"), //
	//
	JUST_HOG("CSAK_SERTES_2_3"), //
	JUST_HEN("CSAK_TYUK_50_60"), //
	JUST_GRAPE("CSAK_SZOLO_1000_1100"), //
	JUST_FRUITY("CSAK_GYUMOLCSOS_2500_2750"), //
	START_WEB("INTERNETEN_MEGKEZDETT"), //
	//
	ARABLE_LAND("SZANTO_TERULET"), //
	GARDEN("KONYHAKERT_TERULET"), //
	FRUITY("GYUMOLCSOS_TERULET"), //
	GRAPE("SZOLO_TERULET"), //
	LAWN("GYEP_TERULET"), //
	FOREST("ERDO_TERULET"), //
	FISHPOND("HALASTO_TERULET"), //
	REED("NADAS_TERULET"), //
	//
	COW("SZARVASMARHA_ALLOMANY"), //
	HOG("SERTES_ALLOMANY"), //
	SHEEP("JUH_ALLOMANY"), //
	GOAT("KECSKE_ALLOMANY"), //
	OSTRICH("STRUCC_ALLOMANY"), //
	HEN("TYUK_ALLOMANY"), //
	TURKEY("PULYKA_ALLOMANY"), //
	DUCK("KACSA_ALLOMANY"), //
	GOOSE("LIBA_ALLOMANY"), //
	RABBIT("NYUL_ALLOMANY"),

	AGRICULTURE("MG_SZOLGALTATAS")

	;
	private String externalFieldId;

	VisitStatusSendAcField(final String externalFieldId) {
		this.externalFieldId = externalFieldId;
	}

	@Override
	public String getFieldId() {
		return this.externalFieldId;
	}

}
