 spring:
   config:
      activate:
         on-profile: dev
   datasource:
      url: jdbc:postgresql://localhost/idgs
      username: idgs
      password: idegS-User5
   jpa:
      show-sql: false
      properties:
         hibernate:
            format_sql: true
   loki:
      url: http://loki:3100

 token:
   secret: 7B8qN35Q2E8YGEycQyFSfUyYd65gYLTN7PsANPtK3sWHsEkuMDSMLmUnU3ZJquUrDknJCVp2FG7MNYpSebZGPGHSQ
   validityMs: 360000000
   
 eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
 management:
  endpoints:
    web:
      exposure:
        include: health, info, logfile, metrics, prometheus # "*" "health,info,logfile,metrics"
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: maja-worklist
    health:
      show-details: always
  tracing:
    sampling:
      probability: 0.0

 server:
  port: 8071

 maja:
  selfLoaderDomain: http://kshdevapp.ksh.hu:8010
  authModul: auth
  
 cors:
  origins: '*'
