spring:
  config:
    activate:
      on-profile: build
  application:
    name: worklist
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: worklist
        jdbc:
          lob:
            non_contextual_creation: true
      org:
        hibernate:
          envers:
            revision_on_collection_change: false
  jackson:
    deserialization:
      adjust_dates_to_context_time_zone: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    database-change-log-table: db_migration
    database-change-log-lock-table: db_migration_lock
    default-schema: ${spring.application.name}
    parameters:
      SCHEMA_NAME: ${spring.application.name}
      app_user: ${spring.datasource.username}
  loki:
    url: http://loki:3100

  datasource:
    username: idgs

token:
  secret: 7B8qN35Q2E8YGEycQyFSfUyYd65gYLTN7PsANPtK3sWHsEkuMDSMLmUnU3ZJquUrDknJCVp2FG7MNYpSebZGPGHSQ
  validityMs: 3600000

server:
  port: 8082
  tomcat:
    remote-ip-header: x-forwarded-for
  http2:
    enabled: true
  shutdown: graceful

jasypt:
  encryptor:
    bean: encryptorBean
logging:
  path: /app/logs

feign:
  client:
    form:
      baseUrl: http://localhost:${wiremock.server.port}
    config:
      default:
        connectTimeout: 60000
        readTimeout: 10000

maja:
  selfLoaderDomain: http://kshdevapp.ksh.hu:8010
#  authModul: auth

cors:
  origins: "*"